#!/usr/bin/env sh
set -eu

hook_dir=$(case "$0" in */*) printf "%s\n" "${0%/*}" ;; *) printf ".\n" ;; esac)
. "${hook_dir}/_common.sh"

cd "$(repo_root)"
run_git diff --cached --check
run_python_checks_if_possible
run_ruff_if_possible
